# Generated by Django 2.2 on 2020-09-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animales'},
        ),
        migrations.AlterModelOptions(
            name='cuidador',
            options={'verbose_name': 'Cuidador', 'verbose_name_plural': 'Cuidadores'},
        ),
        migrations.AlterModelOptions(
            name='limpiador',
            options={'verbose_name': 'Limpiador', 'verbose_name_plural': 'Limpiadores'},
        ),
        migrations.AlterModelOptions(
            name='personal',
            options={'verbose_name': 'Personal', 'verbose_name_plural': 'Personales'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'Sector', 'verbose_name_plural': 'Sectores'},
        ),
    ]
