# Generated by Django 2.2 on 2020-09-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0002_auto_20200925_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='horas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='limpiador',
            name='horas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='personal',
            name='age',
            field=models.IntegerField(),
        ),
    ]
