# Generated by Django 2.2 on 2020-09-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0003_auto_20200925_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='foto',
            field=models.ImageField(blank=True, default='Zoo/default.png', upload_to='Zoo/'),
        ),
    ]
